"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxj+ohfa&@ylctst7seb1&sli2x=yau&#)!zh!wu3olw7)rt-a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG',False)

ALLOWED_HOSTS = [
    'teknovia.ir',
    'www.teknovia.ir',
    'django-backend',
    'teknovia_django',
    'localhost',
    '127.0.0.1',
]
CSRF_TRUSTED_ORIGINS = [
    'https://teknovia.ir',
    'https://www.teknovia.ir',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'imagekit',
    'accounts.apps.AccountsConfig',
    'contents.apps.ContentsConfig',
    'seo.apps.SeoConfig',
    'workflows.apps.WorkflowsConfig',
    'gateway.apps.GatewayConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # باید در بالاترین ردیف ممکن قرار گیرد تا قبل از هر پاسخی هدرها را تزریق کند
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("PG_DB_NAME", "teknovia_db"),
        'USER': os.getenv("PG_DB_USER", "postgres"),
        'PASSWORD': os.getenv("PG_DB_PASSWORD", "postgres_pass"),
        'HOST': os.getenv("DATABASE_HOST", "127.0.0.1"), 
        'PORT': os.getenv("DATABASE_PORT", "5432"),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"), 
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ***** Existing collections ******

CONTENTS = "contents"
RECEIVED = "received"

# ***** Existing collections ******


# Static and Media files configuration
# Serves static and media directly from local directory using filesystem storage backends.

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# SEO Settings
SITE_NAME = 'تکنوویا'
SITE_DESCRIPTION = 'پورتال خبری مدرن هوش مصنوعی و فناوری'
SITE_URL = 'https://teknovia.ir'
LOGO_URL = "/media/logo/teknovia_logo.webp"


# Astro Frontend & Telegram Channel Settings
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://teknica.ir')
TELEGRAM_CHANNEL_USERNAME = os.getenv('TELEGRAM_CHANNEL_USERNAME')


# Telegram API
TELEGRAM_APP_ID = os.getenv('TELEGRAM_APP_ID')
TELEGRAM_APP_HASH = os.getenv('TELEGRAM_APP_HASH')
TELEGRAM_SESSION = os.getenv('TELEGRAM_SESSION')
TELEGRAM_CHANNEL_ID = os.getenv('TELEGRAM_CHANNEL_ID')


# Pagination
NEWS_PER_PAGE = 10
RELATED_NEWS_COUNT = 6


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Storage Configuration
# Configured default engine back to FileSystemStorage for localized server caching and speed.

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# تنظیمات اصلی Celery
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# ────────────────────────────────────────────────────────────────
# پیکربندی تنظیمات CORS (Cross-Origin Resource Sharing)
# ────────────────────────────────────────────────────────────────

# فعال‌سازی دسترسی همگانی در محیط توسعه جهت پیش‌گیری از خطاهای مسدودی مرورگر
# CORS_ALLOW_ALL_ORIGINS = True

# لیست دامنه‌ها و پورت‌های مجاز فرانت‌آسترو برای ارتباطات پیشرفته مرورگر
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:4321",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:4321",
    "https://teknovia.ir",
]

# مجاز بودن ارسال کوکی‌ها و اطلاعات احراز هویت در هدر درخواست‌ها
CORS_ALLOW_CREDENTIALS = True

# هدرهای پیش‌فرض و سفارشی معتبر
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "authorization",
    "x-requested-with",
]