# Generated by Django 6.0.6 on 2026-07-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('telegram_group_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='شناسه آلبوم تلگرام')),
                ('links', models.TextField(blank=True, null=True)),
                ('is_tech', models.BooleanField(default=False)),
                ('is_exists', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('step', models.PositiveSmallIntegerField(choices=[(1, 'tech_check'), (2, 'exists_check'), (3, 'fetching_links'), (4, 'analyzing_medias'), (5, 'saving_medias'), (6, 'finished')], default=1)),
                ('external_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='شناسه اختصاصی بردار (TurboVec)')),
                ('embedding_data', models.BinaryField(blank=True, null=True, verbose_name='امبدینگ کل سند')),
                ('medias', models.ManyToManyField(to='contents.mediacontainer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع فرآیند')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('timeline_events', models.JSONField(blank=True, default=list, verbose_name='رویدادهای تایم\u200cلاین')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا و جزئیات فنی')),
                ('status', models.CharField(choices=[('RUNNING', 'در حال اجرا'), ('COMPLETED', 'موفقیت\u200cآمیز'), ('FAILED', 'خطا در اجرا'), ('SKIPPED', 'رد شده (اسکیپ)')], default='RUNNING', max_length=20, verbose_name='وضعیت کل فرآیند')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_log', to='workflows.receivedmessages', verbose_name='پیام تلگرامی مرتبط')),
            ],
            options={
                'verbose_name': 'لاگ اجرای ورک\u200cفلو',
                'verbose_name_plural': 'لاگ\u200cهای اجرای ورک\u200cفلو',
                'ordering': ['-created_at'],
            },
        ),
    ]
