# Generated by Django 6.0.6 on 2026-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('gemini', 'جمنای'), ('groq', 'گراک'), ('jina', 'جینا'), ('deepseek', 'دیپ سیک'), ('openrouter', 'اوپن روتر')], max_length=30)),
                ('today_use', models.IntegerField(default=0)),
                ('total_use', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
