# Generated by Django 6.0.6 on 2026-07-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicontainer',
            name='provider',
            field=models.CharField(choices=[('gemini', 'جمنای'), ('groq', 'گراک'), ('jina', 'جینا'), ('deepseek', 'دیپ سیک'), ('openrouter', 'اوپن روتر'), ('deapi', 'Deapi')], max_length=30),
        ),
    ]
