# Generated by Django 6.0.6 on 2026-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_apicontainer_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicontainer',
            name='provider',
            field=models.CharField(choices=[('gemini', 'جمنای'), ('groq', 'گراک'), ('jina', 'جینا'), ('deepseek', 'دیپ سیک'), ('openrouter', 'اوپن روتر'), ('deapi', 'Deapi'), ('tavily', 'Tavily'), ('serper', 'Serper')], max_length=30),
        ),
    ]
