# Generated by Django 6.0.6 on 2026-07-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_apicontainer_provider'),
        ('contents', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرستنده')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل فرستنده')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'در حال بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='UNDER_REVIEW', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک کامنت')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.content', verbose_name='محتوا')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.comment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
