# Generated by Django 6.0.6 on 2026-06-22 11:21

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], max_length=20)),
                ('media', models.FileField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='رسانه')),
                ('is_used', models.BooleanField(default=False)),
                ('source_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('icon', models.URLField(blank=True, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('indexable', models.BooleanField(default=True, verbose_name='قابل ایندکس')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contents.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا (مارک\u200cداون)')),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=10, unique=True, verbose_name='کد کوتاه اشتراک گذاری')),
                ('schema_type', models.CharField(blank=True, choices=[('News', 'خبر'), ('Article', 'مقاله')], default='News', max_length=50, verbose_name='نوع Schema')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL کانونیکال')),
                ('media_thumbnail', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/thumbnails/', verbose_name='تامبنیل رسانه')),
                ('media_image_small', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/smalls/', verbose_name='عکس کوچک')),
                ('author', models.CharField(default='خبرگزاری شما', max_length=70, verbose_name='نویسنده')),
                ('indexable', models.BooleanField(default=True, verbose_name='قابل ایندکس')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('importance', models.IntegerField(choices=[(1, 'عادی'), (2, 'فوری'), (3, 'ویژه')], default=1, verbose_name='اهمیت')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='زمان مطالعه')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اشتراک\u200cگذاری')),
                ('external_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='شناسه اختصاصی بردار (TurboVec)')),
                ('embedding_data', models.BinaryField(blank=True, null=True, verbose_name='امبدینگ کل سند')),
                ('category', models.ManyToManyField(to='contents.category', verbose_name='دسته\u200cبندی')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها')),
                ('featured_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_contents', to='contents.mediacontainer', verbose_name='رسانه اصلی')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتواها',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
