# Generated by Django 6.0.6 on 2026-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_mediacontainer_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontainer',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
