# Generated by Django 6.0.6 on 2026-07-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_mediacontainer_is_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='suggestions_status',
            field=models.CharField(blank=True, choices=[('no suggestions', 'بدون پیشنهاد'), ('waiting for generating images', 'منتظر ساخت عکس'), ('processing generated images', 'آنالیز عکس ها و ذخیره سازی'), ('failed', 'فرآیند با خطا مواجه شد'), ('finished generating images', 'اتمام ساخته شدن')], default='no suggestions', max_length=30),
        ),
        migrations.CreateModel(
            name='PostsContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('DRAFT', 'پیش نویس'), ('SENT', 'ارسال شده')], default='DRAFT', max_length=10)),
                ('suggestions_status', models.CharField(blank=True, choices=[('no suggestions', 'بدون پیشنهاد'), ('waiting for generating images', 'منتظر ساخت عکس'), ('processing generated images', 'آنالیز عکس ها و ذخیره سازی'), ('failed', 'فرآیند با خطا مواجه شد'), ('finished generating images', 'اتمام ساخته شدن')], default='no suggestions', max_length=30)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('main_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.content')),
                ('medias', models.ManyToManyField(to='contents.mediacontainer')),
            ],
        ),
    ]
