# Generated by Django 6.0.6 on 2026-07-04 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_suggestions_content_suggestions_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='receiver.receivedmessages', verbose_name='منبع پیام دریافتی'),
        ),
        migrations.AddField(
            model_name='postscontainer',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='receiver.receivedmessages', verbose_name='منبع پیام دریافتی'),
        ),
    ]
