# Generated by Django 6.0.6 on 2026-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_content_data_source_postscontainer_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontainer',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
