# Generated by Django 6.0.6 on 2026-07-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_mediacontainer_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='content',
            name='featured_media',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='postscontainer',
            name='main_article',
        ),
        migrations.RemoveField(
            model_name='postscontainer',
            name='medias',
        ),
        migrations.RemoveField(
            model_name='postscontainer',
            name='data_source',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
