# Generated by Django 6.0.6 on 2026-07-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_remove_content_category_remove_content_data_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaContainer',
        ),
        migrations.DeleteModel(
            name='PostsContainer',
        ),
    ]
