# Generated by Django 6.0.6 on 2026-07-08 04:11

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0009_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='workflows.receivedmessages', verbose_name='منبع پیام دریافتی'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='content',
            name='featured_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_contents', to='contents.mediacontainer', verbose_name='رسانه اصلی'),
        ),
        migrations.AddField(
            model_name='postscontainer',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='workflows.receivedmessages', verbose_name='منبع پیام دریافتی'),
        ),
        migrations.AddField(
            model_name='postscontainer',
            name='main_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.content'),
        ),
        migrations.AddField(
            model_name='postscontainer',
            name='medias',
            field=models.ManyToManyField(to='contents.mediacontainer'),
        ),
    ]
