# Generated by Django 6.0.6 on 2026-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_contenttag_alter_category_options_category_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='آیکون دسته\u200cبندی (SVG یا تصویر)'),
        ),
    ]
