# Generated by Django 6.0.6 on 2026-07-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_category_options_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedcontent',
            name='object_id',
        ),
    ]
