# Generated by Django 6.0.6 on 2026-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_remove_taggedcontent_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='taggedcontent',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedcontent',
            name='content_object',
        ),
        migrations.DeleteModel(
            name='ContentTag',
        ),
        migrations.DeleteModel(
            name='TaggedContent',
        ),
    ]
