# Generated by Django 6.0.6 on 2026-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_tag_remove_content_tags_remove_taggedcontent_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contents', to='contents.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
