# Generated by Django 6.0.6 on 2026-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_content_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(default='تک\u200cنیکا', max_length=70, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
    ]
